jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    GO111MODULE: on # Enable Go Modules
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - script: |
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
    displayName: 'Set up the Go workspace For Unix'
    condition: ne( variables['Agent.OS'], 'Windows_NT' )
  - powershell: |
      New-Item -Path $env:modulePath -ItemType Directory -Force
      Get-ChildItem -Exclude "gopath" -Force | Move-Item -Destination $env:modulePath
      New-Item -Path $env:GOPATH/pkg -ItemType Directory -Force
    displayName: 'Set up the Go workspace For Windows'
    condition: eq( variables['Agent.OS'], 'Windows_NT' )
  - script: |
      go mod verify
      go mod tidy
      go test -v ./...
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies, then run tests'
