jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    GO111MODULE: on # Enable Go Modules
    GOPATH: '$(system.defaultWorkingDirectory)/gopath' # Go workspace path
    modulePath: '$(GOPATH)/src/github.com/$(build.repository.name)' # Path to the module's code

  steps:
  - script: |
      mkdir -p '$(modulePath)'
      shopt -s extglob
      mv !(gopath) '$(modulePath)'
    displayName: 'Set up the Go workspace'

  - script: make test
    workingDirectory: '$(modulePath)'
    displayName: 'Get dependencies, then run tests'
